name: Boa Vista Cloud Factory (Android APK)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:     

jobs:
  build-android:
    name: Assembleer de APK
    runs-on: ubuntu-latest 

    steps:
      - name: Code ophalen uit het magazijn
        uses: actions/checkout@v4
        with:
          submodules: true 

      - name: Java & Android SDK instellen
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compileer C++ naar Android Native Code
        env:
          ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/25.2.9519653 
        run: |
          cmake -B build-android -G Ninja -DCMAKE_SYSTEM_NAME=Android -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a -DCMAKE_ANDROID_NDK=$ANDROID_NDK_HOME -DCMAKE_BUILD_TYPE=Release
          cmake --build build-android --target BoaVista_apk

      - name: Zet de APK klaar voor download
        uses: actions/upload-artifact@v4
        with:
          name: BoaVista-Android-APK
          path: build-android/**/*.apk 
